getwd()
setwd("C:/Users/backmall/Documents/RStudioProject")
df_raw <- read.csv("breast-cancer.data", header = F, stringsAsFactors = F, quote = "'")
table(df_raw)
names(df_raw) <- c("class", "age", "menopause", "tumor_size", "involved_nodes", "through_capsule", "grade", "side", "position", "radiotherapy")
table(df_raw$age)
age_c <- df_raw$age
age_c <- sub("10-19", 1, age_c)
age_c <- sub("20-29", 2, age_c)
age_c <- sub("30-39", 3, age_c)
age_c <- sub("40-49", 4, age_c)
age_c <- sub("50-59", 5, age_c)
age_c <- sub("60-69", 6, age_c)
age_c <- sub("70-79", 7, age_c)
age_c <- sub("80-89", 8, age_c)
age_c <- sub("90-99", 9, age_c)
head(age_c)
age_c <- as.numeric(age_c)
table(df_raw$age)
table(age_c)
table(df_raw$menopause)
menopause_c <- as.factor(df_raw$menopause)
menopause_c <- sub("ge40", "after40", menopause_c)
menopause_c <- sub("lt40", "before40", menopause_c)
menopause_c <- as.factor(menopause_c)
table(df_raw$tumor_size)
convert_range <- function(vect){
  aux_1 <- strsplit(vect, "-")
  aux_2 <- lapply(aux_1, function(x) as.numeric(x))
  convert <- sapply(aux_2, mean)
  return(convert)
}
tumor_size_c <- convert_range(df_raw$tumor_size)
head(tumor_size_c)
table(df_raw$involved_nodes)
involved_nodes_c <- convert_range(df_raw$involved_nodes)
table(df_raw$through_capsule)
through_capsule_c <- df_raw$through_capsule
through_capsule_c[through_capsule_c == "?"] <-NA
table(through_capsule_c)
table(through_capsule_c, useNA = "always")
through_capsule_c <-ifelse(through_capsule_c == "yes", T, F)
table(through_capsule_c, useNA = "always")
table(df_raw$grade)
table(df_raw$side)
table(df_raw$position)
position_c <- df_raw$position
position_c[position_c == "?"] <-NA
table(position_c, useNA = "always")
table(df_raw$radiotherapy)
radiotherapy_c <- df_raw$radiotherapy
radiotherapy_c <- ifelse(radiotherapy_c == "yes", T, F)
table(radiotherapy_c)
table(df_raw$class)
class_c <- df_raw$class
class_c <- ifelse(class_c == "recurrence-events", T, F)
table(class_c)
df1 <-data.frame(class_c, age_c, menopause_c, tumor_size_c, involved_nodes_c, through_capsule_c, df_raw$grade, df_raw$side, position_c, radiotherapy_c)
View(df1)
names(df1) <- c("class/recurrence", "age", "menopause", "tumor_size", "involved_nodes", "through_capsule", "grade", "side", "position", "radiotherapy")
str(df1)
head(df1)
summary(df1)
table(df1$`class/recurrence`)
with(df1, table(df1$`class/recurrence`, df1$radiotherapy, dnn = c("recurrence", "radiotherapy")))